export interface Invoiceproduct {
  id: string
  product_id: string
  cod: string
  quantity: number
  product: string
  unit_cost: number
  unit_price: number
  discount: number
  discount_percentage: number
  price_with_discount: number
  taxes: number
  taxes_percent: number
  subtotal: number
  total: number
  total_recorded: number
  total_no_recorded: any
  total_no_subject: any
  total_exempt: any
  ticket_order_id: string
  employee_id: string
  casheir_id: any
  delivery_id: any
  client_id: string
  referred_id: any
  lot_id: any
  product_type: number
  operation_type: number
  commission: any
  is_commission_payed: number
  comment: any
  is_temporal: number
  special: number
  group_by: any
  status: number
  created_at: string
  updated_at: string
}